name: Push to Branch

on:
  create:
  push:
    branches-ignore:
      - main

env:
  DBT_PROFILES_DIR: ./ci/stage

  DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
  DBT_SNOWFLAKE_USER: ${{ secrets.DBT_SNOWFLAKE_USER }}
  DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}
  DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}
  DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}

  DBT_DATABASE_PROD: ${{ secrets.DBT_DATABASE_PROD }}

jobs:
  dbt_seed_run_test:
    name: "dbt seed, run & test"
    runs-on: ubuntu-latest

    steps:
    - name: 📬 Check out
      uses: actions/checkout@v4

    - name: Extract branch name
      run: echo "CI_CONTEXT=$(echo br_${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV

    - name: 🧩 Install Python and required depencies
      uses: ./.github/actions/install_dependencies
    
    - name: 🌱 Prepare Database
      run: >-
        dbt run-operation clone_database --args 
        '{ 
        source_db: ${{ env.DBT_DATABASE_PROD }}, 
        target_db: ${{ env.DBT_DATABASE_PROD }}_ci_${{ env.CI_CONTEXT }},
        grant_all_to_role: dev_${{ env.DBT_DATABASE_PROD }}
        }'
    
    - name: 📦 Run dbt actions
      uses: ./.github/actions/dbt_full_run
