name: Push to Main Branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: ./ci/prod

  DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
  DBT_SNOWFLAKE_USER: ${{ secrets.DBT_SNOWFLAKE_USER }}
  DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}
  DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}
  DBT_SNOWFLAKE_WAREHOUSE_PROD: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE_PROD }}
  DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
  
  DBT_DATABASE_PROD: ${{ secrets.DBT_DATABASE_PROD }}

jobs:
  dbt_seed_run_test:
    name: "dbt seed, run & test"
    runs-on: ubuntu-latest

    steps:
    - name: 📬 Check out
      uses: actions/checkout@v4

    - name: 🧩 Install Python and required depencies
      uses: ./.github/actions/install_dependencies
    
    - name: 📦 Run dbt actions
      uses: ./.github/actions/dbt_full_run

    - name: Upload documentation
      uses: actions/upload-pages-artifact@v3
      with:
        path: target